### ISSUE TITLE
aarch64/arm64 support

### ISSUE THREAD

**Issue by brandonros** [hiveco/conntrack_exporter#23]
```
conntrack_exporter         | exec /usr/bin/conntrack_exporter: exec format error
```

# docker-compose.yaml

```yaml
  conntrack_exporter:
    container_name: conntrack_exporter
    image: hiveco/conntrack_exporter:0.3.1
    command: --bind-address 0.0.0.0 --listen-port 9318
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: host
    ports:
      - 9318:9318
    logging: *loki-logging
```
